server:
  port: 8090

spring:
  application:
    name: jwt-auth-service

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 1200000  # 20 minutes in milliseconds

logging:
  level:
    com.example.jwtauth: DEBUG
    org.springframework.security: DEBUG